### ISSUE TITLE
Problem z niektórymi serwisami GISON

### ISSUE THREAD

**Issue by zibik** [osm-pl/osm-addr-tools#37]
Przy niektórych wdrożeniach z tej firmy skrypt sobie nie radzi np.
$ ./merger.py --gison gorlice --terc 1205011
Traceback (most recent call last):
  File "./merger.py", line 938, in <module>
    main()
  File "./merger.py", line 897, in main
    data = dataFunc()
  File "./merger.py", line 886, in <lambda>
    dataFunc = lambda: imp.getAddresses()
  File "/home/zibi/osm-tools/impa/osm-addr-tools/punktyadresowe_import.py", line 410, in getAddresses
    data = self.fetchTiles()
  File "/home/zibi/osm-tools/impa/osm-addr-tools/punktyadresowe_import.py", line 1071, in fetchTiles
    raise ValueError("Problem fetching data. {0} available to parse, while totalResulsts is {1}. Maxrows was {2}".format(len(data[0]['geonames']), data[0]['totalResultsCount'], maxrows))
ValueError: Problem fetching data. 1 available to parse, while totalResulsts is 0. Maxrows was 20000

**Comment by wiktorn** [comment]
Poprawione w wersji: 570c813642567895803343a639fb147420270244

Zamiast do warstwy **adresygemaOL** wyciągam dane z warstwy **adresy**. Wygląda na to, że to są różne źródła danych (sprawdzałem na gminie Brzeziny). Trudno mi powiedzieć, które źródło jest lepsze.

Na przykładzie Gorlic, widać też różnice pomiędzy tym co jest w EMUiA GUGiK, a tym co jest w warstwie **adresy**.

Faktem jest natomiast, że wyszukiwarka na stronie gminy Brzezina wyszukuje w warstwie **adresygemaOL**, a na stronie gminy Gorlice - **adresy**.

Niemniej - zachowanie jakie teraz zaimplementowałem - próbuje najpierw pobrać dane z warstwy **adresygemaOL**, a jeżeli nic nie znajdzie - próbuje w warstwie **adresy**.


Dodatkowo - wprowadziłem też kolejność przetwarzania obiektów, jak i kolejność w pliku wynikowym. Więc jak się uruchomi dwa razy skrypt dla tej samej gminy z tymi samymi parametrami, to różnice zgłaszane przez `diff` są minimalne. Niestety - nie umożliwiło to sensownego porównania **adresy** vs **adresygemaOL** vs EMUiA GUGiK.
