### ISSUE TITLE
Illegal value for attribute 'changeset'. Got 0. 

### ISSUE THREAD

**Issue by zibik** [osm-pl/osm-addr-tools#39]
Przy próbie otwarcia pliku result.osm przygotowanego przez skrypt (venv/bin/python merger.py --impa jaraczewo) dostaję kompunikat:
Illegal value for attribute 'changeset'. Got 0. (w linii 14 590, kolumnie 146). odczytano 1 155 796 bajtów
Przy innych gminach z iMPA też mam tak samo.

**Comment by wiktorn** [comment]
RODO ugryzło. Mój overpass ma ogólnodostępne dump'y, w których nie ma m.in. changeset'a. Możesz spróbować tymczasowo przepiąć się na `overpass-api.de`, a ja tymczasem powalczę, by do mojego overpassa zaciągać pełne metadane.

**Comment by wiktorn** [comment]
Overpass przekręcony, już ma changeset;y i inne metadane. Plik generuje się poprawny.
